version: '3'

services:
  db-container:
    build: ./db
    container_name: 'db-container'
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./db/.env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql

  web-container:
    build: ./web
    container_name: 'web-container'
    restart: always
    depends_on:
      - proxy-container
    ports:
      - "3000"

  read-api-container:
    build: ./read-api
    container_name: 'read-api-container'
    restart: always
    depends_on:
      - proxy-container
      - db-container
    ports:
      - "80"
    env_file:
      - ./db/.env

  write-api-container:
    build: ./write-api
    container_name: 'write-api-container'
    restart: always
    depends_on:
      - proxy-container
      - db-container
    ports:
      - "3000"
    env_file:
      - ./db/.env

  proxy-container:
    build: ./proxy
    container_name: 'proxy-container'
    restart: always
    ports:
      - "80:80"
